### ISSUE TITLE
Make openfoammeshreader an optional dependency

### ISSUE THREAD

**Issue by johnjasa** [mdolab/idwarp#8]
## Type of issue

- Bugfix (non-breaking change which fixes an issue)

## Description

Currently, the reg tests require that you have openfoammeshreader installed, but it's not listed as a dependency. Either have it be a dependency or refactor the regression tests so that it is not needed.

### Steps to reproduce issue
Run the reg tests without openfoammeshreader installed.

### Current behavior
The reg tests fail without that package, without a good error message

### Expected behavior
Reg tests should pass

**Comment by johnjasa** [comment]
@nwu63, I made an issue for this, I'll try to figure out how best to do this

**Comment by nwu63** [comment]
This has been fixed as part of #13. When we switch to `testflo` we will implement test skipping properly.

**Comment by nwu63** [comment]
Nevermind, this fix was not done correctly. By skipping the test the comparison will fail, so let's fix this after moving to testflo so we can do skipping properly.

**Comment by friedenhe** [comment]
I think we can close this issue. The openfoammeshreader repo has been renamed to pyofm, and we made the idwarp's reg_test independent of pyofm. Basically, we moved the reg_test from idwarp to pyofm, i.e., idwarp no longer tests pyofm. pyofm is now optional because it will be loaded only if you use DAFoam.
